logging:
  config: /etc/simple/logback-spring.xml

#redis参数配置
spring:
  datasource:
    url: jdbc:mysql://test.koudaibook.com:30006/mydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Password!&
  redis:
    host: manager.e-healthcare.net
    password: meetinglive
    port: 31379

server:
  port: 80