logging:
  config: /etc/staffjoy/logback-spring.xml

#redis参数配置
redis:
  hostName: 47.101.223.234
  redisport: 6379
  passWord: meetinglive
  maxActive: 800
  maxIdle: 100
  maxWait: 1000
  testOnBorrow: true